config/routes.rb
Rails.application.routes.draw do
  post 'events/new', to: 'events#create'
  root 'users#index'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :users
  resources :events
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee

  scope :past, -> { where('date < :current_time', current_time: DateTime.now) }
  scope :upcoming, -> { where('date >= :current_time', current_time: DateTime.now) }
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :password_digest, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name, presence: true
  validates :email, presence: true

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations, source: :attended_event

  def upcoming_events
    attended_events.where('date >= :current_time', current_time: DateTime.now)
  end

  def previous_events
    attended_events.where('date < :current_time', current_time: DateTime.now)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
    redirect_to user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.all
    @upcoming = Event.upcoming
    @past = Event.past
    @current_user = current_user
  end

  def new
    @event = Event.new
    @current_user = current_user
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @current_user = current_user
    @checked = (@event.creator || @event.attendees.include?(@current_user)) && logged_in?
    @users = User.all
    @invitation = current_user.invitations.build if logged_in?
    @invited = @event.attendees
  end

  private

  def event_params
    params.require(:events).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  def create
    @invitation = current_user.invitations.build(invitation_params)
    if @invitation.save
      flash[:success] = 'Invitation sent!'
      redirect_to current_user
    else
      flash.now[:danger] = 'There was a problem with your invite. Try again.'
      redirect_to events_index_url
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:attendee_id, :attended_event_id, :host_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:name])
    if user
      log_in(user)
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'Successfully logged out!'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @current_user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to signin_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @invitations = @user.invitations
    @events = @user.created_events
    @invites = @user.attended_events
    @current_user = current_user
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/invitation_helper.rb
# frozen_string_literal: true

module InvitationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb


<% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>

<% if !@upcoming.empty? %>
<h2>These are the upcoming events</h2>
    <ul>

        <% @upcoming.each do |event| %>
    
        <li><%= link_to event.title , event %></li>
    
        <% end %>

    </ul>

<% end %> 

<% if !@past.empty? %>
<h2>These are the past events</h2>
    <ul>

        <% @past.each do |event| %>
    
        <li><%= link_to event.title , event %></li>
    
        <% end %>

    </ul>
<% end %>

app/views/events/new.html.erb
<% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>


<h1>Create a new event</h1>

<%= form_for(:events) do |f| %>
  <%= f.label :title, "Name of the event" %>
  <%= f.text_field :title %> <br>

  <%= f.label :description, "Add the event description" %>
  <%= f.text_area :description %> <br>

  <%= f.label :date, "Date of the event" %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>

<h2> Name of Event: <%= @event.title%> </h2>

This event was created by  <b><%= @event.creator.name.capitalize %></b>
<br>
<% if @invited.empty? %>
No invitations have been made



<% else %>
The following people will be attending:
<br>
<ul>
		<% @event.attendees.each do |attendee| %>
		<li><%= attendee.name %> </li>
		<% end %>
	</ul>	
	
	<% end %>
	
	<% if @checked %>
<%= form_for(@invitation) do |f| %>
	<%= f.hidden_field :attended_event_id, value: @event.id %>
	<%= f.hidden_field :host_id, value: @current_user.id %>
	<%= f.label :attendee_id, 'Invite:' %>
	<%= f.select :attendee_id, options_for_select(@users.map do |user|
	                           [user.name, user.id]
				                   end),
															{ :prompt => 'Select friend' } %>
	<%= f.submit 'Invite' %>
<% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header2.html.erb
<div class="nav">
    <div class='logo'>  <a class='li'> EventRiteApp </a></div>
           
            <%= link_to 'Sign In', signin_path, class: 'li check' %>
  
            <%= link_to 'Sign Up', new_user_url, class: 'li check' %>
            <%= link_to 'Events', events_url, class: 'li check' %> 
             <%= link_to 'Home', root_path, class: 'li check' %>

</div>
    
          


app/views/layouts/_headings.html.erb
<div class="nav">
    <%= link_to 'Home', root_path, class: 'li check' %>
    <%= link_to 'View all Events', events_url, class: 'li check' %>
  <%= link_to  "Sign Out", signout_path , method: :delete , class: 'li check' %></h2>   
   <%= link_to  "Create event", events_new_url, class: 'li check' %>
</div>
       
      
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Liu+Jian+Mao+Cao&family=Oswald:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
      const check = document.querySelectorAll('.check')
      
      check.forEach(element => {
        element.addEventListener("mouseover", function(e) {
       e.target.classList.add('animated', 'heartBeat','red');
       console.log(check.className)
      })
      element.addEventListener('mouseout',function(e) {
       e.target.classList.remove('red','animated', 'heartBeat')
      })
      });
      
     </script>
  </body>
  
</html>

app/views/users/index.html.erb

<div class="body">
    <% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>
<div class="pinky">
    <div class="own">
    <p>  CREATE YOUR EVENTS </p> 
    <p>  INVITE YOUR FRIENDS </p>  
    </div>
    <div class="own own2 ">
        <p>  CHECK OUT THE LATEST EVENTS </p> 
         
    </div>
    <div class="own">
        <p>  RECEIVE INVITATIONS </p> 
        <p>  ATTEND IF YOU WISH </p> 
       
    </div>
</div>
    <div class="intro">
        <b>EventRite</b> - An app that lets you plan your events, put them into your calendar,
        invite the people you want and manage all intricacies.
    </div>
</div>



app/views/users/new.html.erb


<%= link_to 'Home', root_path %>
<%= link_to 'View All Events', events_path %>
<%= link_to 'Sign In', signin_path %>

<h1> Sign Up Here</h1>

<%= form_for @user do |f| %>
<%= render 'layouts/error_messages' %>
  <%= f.label :name, 'Enter your name' %>
  <%= f.text_field :name %>  
<br><br>
  <%= f.label :email, 'Enter your email' %>
  <%= f.email_field :email %>  
  <br><br>
  <%= f.label :password_digest, 'Enter your password' %>
  <%= f.password_field :password_digest %>
  <br><br>
 
  <%= f.submit  'Create your account'%>

<% end %>

app/views/users/show.html.erb
<% if !@current_user.nil? %>
<%= render 'layouts/headings' %>
<% end %>

<h1>You are welcome <%= @user.name %></h1>

<% if !@events.empty? %>
<h3>You created the following events</h3>
<ul>
<% @events.each do |event| %>
<li> <%= link_to event.title , event %></li>
 
<% end %>
</ul>
   <br>
<% else %>
<h3>You have not created any events</h3>
 
<% end %>

<% if @invitations.empty? %>
<h3>You have not been invited to any events</h3>
<% end %>

<% if !@invites.empty? %>

<% if !@upcoming_events.empty? %>
<ul>
<h3>You have been invited to the following upcoming events</h3>


<% @upcoming_events.each do |event| %> 
  <li><%= link_to event.title , event %> </li>
<% end %>
</ul>

<% end %>


<% if !@previous_events.empty? %>
<ul>
  <h3>You attended the following events:</h3>
  
  
  <% @previous_events.each do |event| %> 
    <li><%= link_to event.title , event %> </li>
  <% end %>
</ul>

<% end %>

<% end %>

